SetTimer,UPDATEDSCRIPT,5000 

UPDATEDSCRIPT: 
FileGetAttrib,attribs,%A_ScriptFullPath% 
IfInString,attribs,A 
{ 
FileSetAttrib,-A,%A_ScriptFullPath% 
Reload 
} 
Return 

CapsLock::Return
#if GetKeyState("CapsLock","P")
q::SendInput,q
w::SendInput,w
e::SendInput,e
r::SendInput,r
t::SendInput,t
y::SendInput,y
u::SendInput,u
i::SendInput,i
o::SendInput,o
p::SendInput,p
[::SendInput,[
]::SendInput,]
\::SendInput,\
a::SendInput,a
s::SendInput,s
d::SendInput,d
f::SendInput,f
g::SendInput,g
h::SendInput,{Left}
j::SendInput,{Down}
k::SendInput,{Up}
l::SendInput,{Right}
;::SendInput,;
'::SendInput,'
z::SendInput,z
x::SendInput,x
c::SendInput,c
v::SendInput,v
b::SendInput,b
n::SendInput,n
m::SendInput,m
,::SendInput,,
.::SendInput,.
/::SendInput,/